Feature/password handling
skhomm/wifi-clients-test-suite pull request #1
Opened 2020-12-16 06:36 UTC by skhomm

Completed task "Secure login and password handling" from board "2. APs management algorithm" + minor cosmetic changes.

2020-12-17 14:49 UTC, technogleb requested changes
В целом, ок, можно подумать над большей модульностью и переиспользуемостью кода. 
И еще, прикрутите себе линтеры, pylint или flake8

2020-12-17 14:49 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>  replay = 2
глобальные константы пишутся капсом

2020-12-17 14:49 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>          for tx_power in range (max_power, min_power, step_power):
Здесь еще забыл пробел убрать))

2020-12-17 14:49 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>      for device in (aruba_1, aruba_2):
вот все, что внутри этого цикла будет более читабельно запихнуть в функцию `def run_device(device: dict):`

2020-12-17 14:49 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>              listed_output=output.split("\n")
NoNoNo. Напиши просто 
`for line in output.split("\n"): print(line)`

2020-12-17 14:49 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>  from netmiko import ConnectHandler
стандартные и сторонние импорты разделяются пустой строкой

2020-12-17 14:49 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>          ap_counter+=1
Пробелы

2020-12-18 06:57 UTC, skhomm commented on make_roam/aruba/make_roam_aruba_IAP.py
>              listed_output=output.split("\n")
А если мне нужно вывести только первые 3 строки?

2020-12-18 08:38 UTC, skhomm commented on make_roam/aruba/make_roam_aruba_IAP.py
>  from netmiko import ConnectHandler
Есть ли быстрый способ понять является ли импорт стандартным или сторонним?

2020-12-18 08:39 UTC, skhomm commented on make_roam/aruba/make_roam_aruba_IAP.py
>  replay = 2
Если переменная никогда не меняется в коде после первого назначения — это глобальная константа?
К глобальным константам относятся те, которые вводятся пользователем с клавиатуры?

2020-12-18 18:30 UTC, skhomm commented
Исправил замечания и добавил кучу исправлений.
Из крупных:
- добавил модульности при помощи функций
- использовал внешний файл для базы устройств

2020-12-19 08:23 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>  replay = 2
1) Да
2) Нет

2020-12-19 08:24 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>              listed_output=output.split("\n")
[:3]

2020-12-19 08:25 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
>  from netmiko import ConnectHandler
Обычно ты это просто знаешь, но вообще ты можешь получить у импортированного модуля атрибут __file__, если там в пути есть site-packages - он сторонний

2020-12-22 06:25 UTC, skhomm commented
Собрал разбросанное тело программы в одном месте.
Думаю, что if __name__ == “main” здесь не нужен, так как программа, как раз, будет запускаться как внешний модуль.

2020-12-22 08:32 UTC, skhomm commented
Пришли к соглашению, что if __name__ == __main__, всё-таки, нужен.

2020-12-22 11:36 UTC, technogleb approved these changes
Гуд!

2020-12-22 11:36 UTC, merged