Feature/main module
skhomm/wifi-clients-test-suite pull request #2
Opened 2020-12-28 05:07 UTC by skhomm

Add main module to start all future submodules (including existing make_roam_aruba_IAP).
Put all configuration variables in the separate file (config.py).
Get rid of CHANNEL and ap_counter.
Some minor refactoring.

2021-01-04 11:13 UTC, technogleb requested changes
В целом все ок, поправь замечание про импорт, и все.

2021-01-04 11:13 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
> +try:
Так, никаких костылей такого рода. Пиши импорт относительно корня проекта. Либо относительные импорты с точкой, но первое в небольших проектах предпочтительнее.

```suggestion
from make_roam.aruba import config
```

Напоминаю, что при установке импорта в корень проекта, тебе далее при запуске необходимо будет установить PYTHONPATH в корень проекта для каждого терминала в котором делаешь запуск. Или настроить это в IDE, pycharm например делает это автоматически.

2021-01-06 12:06 UTC, skhomm commented on make_roam/aruba/make_roam_aruba_IAP.py
> +try:
Я бы и рад, но есть два ограничения:

1. Я не хочу использовать PYTHONPATH так как проект будет запускаться на самых разных машинах самыми разными людьми. Не хочу заставлять их выполнять какие-то дополнительные манипуляции.
2. Я хочу чтобы можно было запустить как основной модуль, так и отдельно make_roam/aruba/make_roam_aruba_IAP.py
Если использовать относительные импорты с точками в главном модуле, будут проблемы с внутренними импортами в make_roam/aruba/make_roam_aruba_IAP.py, так как текущая рабочая директория будет не make_roam/aruba/

Погуглив тему я не нашёл ничего умнее чем использование конструкции типа
try:
    import config
except ImportError:
    from . import config

Есть варианты как сделать лучше с учётом описанных ограничений?

2021-01-07 11:51 UTC, technogleb commented on make_roam/aruba/make_roam_aruba_IAP.py
> +try:
Конечно есть.
1) Заставлять прописывать пользователя дополнительные инструкции абсолютно нормально, обычно это указывается в README.md. Можешь посмотреть популярные опенсорс проекты на питоне и увидишь, что многие авторы указывают кучу доп. инструкций перед запуском. Чтобы запустить тот же фласк, нужно сначала экспортировать две переменные окружения. Тем не менее, если ты хочешь автоматизировать этот процесс у тебя есть несколько опций
- написать скрипт start.sh в котором ты за пользователя пропишешь все переменные, и ему останется лишь запустить этот скрипт перед началом работы
- в каждом файле перед импортами прописать добавление корня проекта в sys.path
`import sys; sys.path.append("путь до корня проекта")`

2) Именно по этому я прошу писать абсолютные импорты, так как они не зависят от того, где ты запускаешь код.

2021-01-09 10:20 UTC, technogleb approved these changes
Все гуд!

2021-01-09 10:23 UTC, merged