Feature/assoc req
skhomm/wifi-clients-test-suite pull request #6
Opened 2021-01-23 01:24 UTC by ttl256

Here a module for catching assoc req and parse it on the fly. Right now supported channels get parsed. Scapy doesn't provide an API to access supported channels so a simple dissector was added to accomplish it.

2021-01-26 12:59 UTC, technogleb requested changes
А в целом все ок.

2021-01-26 12:59 UTC, technogleb commented on client_capabilities/assoc_req.py
> +def write_pcap(frame, pcap_file = "assoc_req.pcap"):
Данная функция дублирует функционал и сигнатуру уже имеющейся.

2021-01-26 12:59 UTC, technogleb commented on client_capabilities/assoc_req.py
> +from scapy.all import *
Даже если модуль поддерживает all лучше импортить более явно, чтобы не засорять пространство имен.

2021-01-26 12:59 UTC, technogleb commented on client_capabilities/assoc_req.py
> +def supported_channels_parse(frame):
parse_supported_channels звучит лучше)

2021-01-26 12:59 UTC, technogleb commented on client_capabilities/assoc_req.py
> +
Отступ между функциями - две строки

2021-01-26 12:59 UTC, technogleb commented on client_capabilities/assoc_req.py
> +def write_pcap(frame, pcap_file = "assoc_req.pcap"):
И мы не обрамляем пробелами знак присваивания в сигнатурах

2021-02-15 20:09 UTC, skhomm approved these changes
We should consider adding an installation guide.

2021-02-15 20:10 UTC, merged